### ISSUE TITLE
zsh output problem

### ISSUE THREAD

**Issue by lidashuang** [xr09/rainbow.sh#2]
run script in the zsh

```
#!/usr/bin/env bash

source rainbow.sh 

info1=$(echored "1. 请运行./xi server -d ./assets/res")
info2=$(echored "2. 需要改updateConfig.lua的devMode为true, center 地址为xi -s 的输出地址, resVersion 为./xi generate  生成数字版本")
info3=$(echored "3. 你需要打一个基于生成的assets版本的apk")

echo $info1
echo $info2
echo $info3
```

but output is 
![image](https://cloud.githubusercontent.com/assets/612381/8961939/9674e188-364a-11e5-8a93-705f4200ef4e.png)

**Comment by xr09** [comment]
![30](https://cloud.githubusercontent.com/assets/1380243/8970806/b6d86fe8-3619-11e5-93c5-6d90a753de5f.png)

Works in my computer (TM). Maybe anything related to your locales?

**Comment by lidashuang** [comment]
![](http://lidashuang.u.qiniudn.com/15-7-30/56472907.jpg)

**Comment by xr09** [comment]
Is the shebang correct in the file?

    $ head -n1 a.sh
    #!/usr/bin/env zsh

**Comment by lidashuang** [comment]
system shell is zsh,  script shell is bash `#!/usr/bin/env bash`

**Comment by xr09** [comment]
Try running `/usr/bin/env bash` from your zsh prompt.
